export const colombia = [
  {
    departamento: "Atlántico",
    ciudades: [
      "Barranquilla",
      "Baranoa",
      "Candelaria",
      "Galapa",
      "Luruaco",
      "Malambo",
      "Manatí",
      "Piojó",
      "Polonuevo",
      "Sabanagrande",
      "Sabanalarga",
      "Santa Lucía",
      "Santo Tomás",
      "Soledad",
      "Suan",
      "Tubará",
      "Usiacurí",
      "Juan de Acosta",
      "Palmar de Varela",
      "Campo de La Cruz",
      "Repelón",
      "Puerto Colombia",
      "Ponedera"
    ]
  },
  {
    departamento: "Amazonas",
    ciudades: [
      "Leticia",
      "El Encanto",
      "La Chorrera",
      "La Pedrera",
      "La Victoria",
      "Puerto Arica",
      "Puerto Nariño",
      "Puerto Santander",
      "Tarapacá",
      "Puerto Alegría",
      "Miriti Paraná"
    ]
  },
  {
    departamento: "Antioquia",
    ciudades: [
      "Medellín",
      "Abejorral",
      "Abriaquí",
      "Alejandría",
      "Amagá",
      "Amalfi",
      "Andes",
      "Angelópolis",
      "Angostura",
      "Anorí",
      "Anzá",
      "Apartadó",
      "Arboletes",
      "Argelia",
      "Armenia",
      "Barbosa",
      "Bello",
      "Betania",
      "Betulia",
      "Ciudad Bolívar",
      "Briceño",
      "Buriticá",
      "Cáceres",
      "Caicedo",
      "Caldas",
      "Campamento",
      "Cañasgordas",
      "Caracolí",
      "Caramanta",
      "Carepa",
      "Carolina",
      "Caucasia",
      "Chigorodó",
      "Cisneros",
      "Cocorná",
      "Concepción",
      "Concordia",
      "Copacabana",
      "Dabeiba",
      "Don Matías",
      "Ebéjico",
      "El Bagre",
      "Entrerríos",
      "Envigado",
      "Fredonia",
      "Giraldo",
      "Girardota",
      "Gómez Plata",
      "Guadalupe",
      "Guarne",
      "Guatapé",
      "Heliconia",
      "Hispania",
      "Itagüí",
      "Ituango",
      "Belmira",
      "Jericó",
      "La Ceja",
      "La Estrella",
      "La Pintada",
      "La Unión",
      "Liborina",
      "Maceo",
      "Marinilla",
      "Montebello",
      "Murindó",
      "Mutatá",
      "Nariño",
      "Necoclí",
      "Nechí",
      "Olaya",
      "Peñol",
      "Peque",
      "Pueblorrico",
      "Puerto Berrío",
      "Puerto Nare",
      "Puerto Triunfo",
      "Remedios",
      "Retiro",
      "Rionegro",
      "Sabanalarga",
      "Sabaneta",
      "Salgar",
      "San Francisco",
      "San Jerónimo",
      "San Luis",
      "San Pedro",
      "San Rafael",
      "San Roque",
      "San Vicente",
      "Santa Bárbara",
      "Santo Domingo",
      "El Santuario",
      "Segovia",
      "Sopetrán",
      "Támesis",
      "Tarazá",
      "Tarso",
      "Titiribí",
      "Toledo",
      "Turbo",
      "Uramita",
      "Urrao",
      "Valdivia",
      "Valparaíso",
      "Vegachí",
      "Venecia",
      "Yalí",
      "Yarumal",
      "Yolombó",
      "Yondó",
      "Zaragoza",
      "San Pedro de Urabá",
      "Santa Fe de Antioquia",
      "Santa Rosa de Osos",
      "San Andrés de Cuerquía",
      "Vigía del Fuerte",
      "San José de la Montaña",
      "San Juan de Urabá",
      "El Carmen de Viboral",
      "San Carlos",
      "Frontino",
      "Granada",
      "Jardín",
      "Sonsón"
    ]
  },
  {
    departamento: "Arauca",
    ciudades: [
      "Arauquita",
      "Cravo Norte",
      "Fortul",
      "Puerto Rondón",
      "Saravena",
      "Tame",
      "Arauca"
    ]
  },
  {
    departamento: "Bogotá D.C.",
    ciudades: ["Bogotá D.C."]
  },
  {
    departamento: "Bolívar",
    ciudades: [
      "Achí",
      "Arenal",
      "Arjona",
      "Arroyohondo",
      "Calamar",
      "Cantagallo",
      "Cicuco",
      "Córdoba",
      "Clemencia",
      "El Guamo",
      "Magangué",
      "Mahates",
      "Margarita",
      "Montecristo",
      "Mompós",
      "Morales",
      "Nerocí",
      "Pinillos",
      "Regidor",
      "Río Viejo",
      "San Estanislao",
      "San Fernando",
      "San Juan Nepomuceno",
      "Santa Catalina",
      "Santa Rosa",
      "Simití",
      "Soplaviento",
      "Talaigua Nuevo",
      "Tiquisio",
      "Turbaco",
      "Turbaná",
      "Villanueva",
      "Barranco de Loba",
      "Santa Rosa del Sur",
      "Hatillo de Loba",
      "El Carmen de Bolívar",
      "San Martín de Loba",
      "Altos del Rosario",
      "San Jacinto del Cauca",
      "San Pablo de Borbur",
      "San Jacinto",
      "El Peñón",
      "Cartagena",
      "María la Baja",
      "San Cristóbal",
      "Zambrano"
    ]
  },
  {
    departamento: "Boyacá",
    ciudades: [
      "Tununguá",
      "Motavita",
      "Ciénaga",
      "Tunja",
      "Almeida",
      "Aquitania",
      "Arcabuco",
      "Berbeo",
      "Betéitiva",
      "Boavita",
      "Boyacá",
      "Briceño",
      "Buena Vista",
      "Busbanzá",
      "Caldas",
      "Campohermoso",
      "Cerinza",
      "Chinavita",
      "Chiquinquirá",
      "Chiscas",
      "Chita",
      "Chitaraque",
      "Chivatá",
      "Cómbita",
      "Coper",
      "Corrales",
      "Covarachía",
      "Cubará",
      "Cucaita",
      "Cuítiva",
      "Chíquiza",
      "Chivor",
      "Duitama",
      "El Cocuy",
      "El Espino",
      "Firavitoba",
      "Floresta",
      "Gachantivá",
      "Gameza",
      "Garagoa",
      "Guacamayas",
      "Guateque",
      "Guayatá",
      "Güicán",
      "Iza",
      "Jenesano",
      "Jericó",
      "Labranzagrande",
      "La Capilla",
      "La Victoria",
      "Macanal",
      "Maripí",
      "Miraflores",
      "Mongua",
      "Monguí",
      "Moniquirá",
      "Muzo",
      "Nobsa",
      "Nuevo Colón",
      "Oicatá",
      "Otanche",
      "Pachavita",
      "Páez",
      "Paipa",
      "Pajarito",
      "Párua",
      "Pauna",
      "Paya",
      "Pesca",
      "Pisba",
      "Puerto Boyacá",
      "Quípama",
      "Ramiriquí",
      "Ráquira",
      "Rondón",
      "Saboyá",
      "Sáchica",
      "Samacá",
      "San Eduardo",
      "San Mateo",
      "Santana",
      "Santa María",
      "Santa Sofía",
      "Sativanorte",
      "Sativasur",
      "Siachoque",
      "Soatá",
      "Socotá",
      "Socha",
      "Sogamoso",
      "Somondoco",
      "Sora",
      "Sotaquirá",
      "Soracá",
      "Susacón",
      "Sutamarchán",
      "Sutatenza",
      "Tasco",
      "Tenza",
      "Tibaná",
      "Tinjacá",
      "Tipacoque",
      "Toca",
      "Tópaga",
      "Tota",
      "Turmequé",
      "Tutazá",
      "Umbita",
      "Ventaquemada",
      "Viracachá",
      "Zetaquira",
      "Togüí",
      "Villa de Leyva",
      "Paz de Río",
      "Santa Rosa de Viterbo",
      "San Pablo de Borbur",
      "San Luis de Gaceno",
      "San José de Pare",
      "San Miguel de Sema",
      "Tuta",
      "Tibasosa",
      "La Uvita",
      "Belén"
    ]
  },
  {
    departamento: "Caldas",
    ciudades: [
      "Manizales",
      "Aguadas",
      "Anserma",
      "Aranzazu",
      "Belalcázar",
      "Chinchiná",
      "Filadelfia",
      "La Dorada",
      "La Merced",
      "Manzanares",
      "Marmato",
      "Marulanda",
      "Neira",
      "Norcasia",
      "Pácora",
      "Palestina",
      "Pensilvania",
      "Riosucio",
      "Risaralda",
      "Salamina",
      "Samaná",
      "San José",
      "Supía",
      "Victoria",
      "Villamaría",
      "Viterbo",
      "Marquetalia"
    ]
  },
  {
    departamento: "Caquetá",
    ciudades: [
      "Florencia",
      "Albania",
      "Curillo",
      "El Doncello",
      "El Paujil",
      "Morelia",
      "Puerto Rico",
      "Solano",
      "Solita",
      "Valparaíso",
      "San José del Fragua",
      "Belén de los Andaquíes",
      "Cartagena del Chairá",
      "Milán",
      "La Montañita",
      "San Vicente del Caguán"
    ]
  },
  {
    departamento: "Casanare",
    ciudades: [
      "Yopal",
      "Aguazul",
      "Chámeza",
      "Hato Corozal",
      "La Salina",
      "Monterrey",
      "Pore",
      "Recetor",
      "Sabanalarga",
      "Sácama",
      "Tauramena",
      "Trinidad",
      "Villanueva",
      "San Luis de Gaceno",
      "Paz de Ariporo",
      "Nunchía",
      "Maní",
      "Támara",
      "Orocué"
    ]
  },
  {
    departamento: "Cauca",
    ciudades: [
      "Popayán",
      "Almaguer",
      "Argelia",
      "Balboa",
      "Bolívar",
      "Buenos Aires",
      "Cajibío",
      "Caldono",
      "Caloto",
      "Corinto",
      "El Tambo",
      "Florencia",
      "Guachené",
      "Guapi",
      "Inzá",
      "Jambaló",
      "La Sierra",
      "La Vega",
      "López",
      "Mercaderes",
      "Miranda",
      "Morales",
      "Padilla",
      "Patía",
      "Piamonte",
      "Piendamó",
      "Puerto Tejada",
      "Puracé",
      "Rosas",
      "Santa Rosa",
      "Silvia",
      "Sotará",
      "Suárez",
      "Sucre",
      "Timbío",
      "Timbiquí",
      "Toribio",
      "Totoró",
      "Villa Rica",
      "Santander de Quilichao",
      "San Sebastián",
      "Páez"
    ]
  },
  {
    departamento: "Cesar",
    ciudades: [
      "Valledupar",
      "Aguachica",
      "Agustín Codazzi",
      "Astrea",
      "Becerril",
      "Bosconia",
      "Chimichagua",
      "Chiriguaná",
      "Curumaní",
      "El Copey",
      "El Paso",
      "Gamarra",
      "González",
      "La Gloria",
      "Manaure",
      "Pailitas",
      "Pelaya",
      "Pueblo Bello",
      "La Paz",
      "San Alberto",
      "San Diego",
      "San Martín",
      "Tamalameque",
      "Río de Oro",
      "La Jagua de Ibirico"
    ]
  },
  {
    departamento: "Chocó",
    ciudades: [
      "Istmina",
      "Quibdó",
      "Acandí",
      "Alto Baudó",
      "Atrato",
      "Bagadó",
      "Bahía Solano",
      "Bajo Baudó",
      "Bojayá",
      "Cértegui",
      "Condoto",
      "Juradó",
      "Lloró",
      "Medio Atrato",
      "Medio Baudó",
      "Medio San Juan",
      "Nóvita",
      "Nuquí",
      "Río Iro",
      "Río Quito",
      "Riosucio",
      "Sipí",
      "Unguía",
      "El Litoral del San Juan",
      "El Cantón del San Pablo",
      "El Carmen de Atrato",
      "San José del Palmar",
      "Belén de Bajirá",
      "Carmen del Darién",
      "Tadó",
      "Unión Panamericana"
    ]
  },
  {
    departamento: "Córdoba",
    ciudades: [
      "San Bernardo del Viento",
      "Montería",
      "Ayapel",
      "Buenavista",
      "Canalete",
      "Cereté",
      "Chimá",
      "Chinú",
      "Cotorra",
      "Lorica",
      "Los Córdobas",
      "Momil",
      "Moñitos",
      "Planeta Rica",
      "Pueblo Nuevo",
      "Puerto Escondido",
      "Purísima",
      "Sahagún",
      "San Andrés Sotavento",
      "San Antero",
      "San Pelayo",  
      "Tierralta",
      "Tuchín",
      "Valencia",
      "San José de Uré",
      "Ciénaga de Oro",
      "San Carlos",
      "Montelíbano",
      "La Apartada",
      "Puerto Libertador"
    ]
  },
  {
    departamento: "Cundinamarca",
    ciudades: [
      "Anapoima",
      "Arbeláez",
      "Beltrán",
      "Bituima",
      "Bojacá",
      "Cabrera",
      "Cachipay",
      "Cajicá",
      "Caparrapí",
      "Caqueza",
      "Chaguaní",
      "Chipaque",
      "Choachí",
      "Chocontá",
      "Cogua",
      "Cota",
      "Cucunubá",
      "El Colegio",
      "El Rosal",
      "Fomeque",
      "Fosca",
      "Funza",
      "Fúquene",
      "Gachalá",
      "Gachancipá",
      "Gachetá",
      "Girardot",
      "Granada",
      "Guachetá",
      "Guaduas",
      "Guasca",
      "Guataquí",
      "Guatavita",
      "Guayabetal",
      "Gutiérrez",
      "Jerusalén",
      "Junín",
      "La Calera",
      "La Mesa",
      "La Palma",
      "La Peña",
      "La Vega",
      "Lenguazaque",
      "Machetá",
      "Madrid",
      "Manta",
      "Medina",
      "Mosquera",
      "Nariño",
      "Nemocón",
      "Nilo",
      "Nimaima",
      "Nocaima",
      "Venecia",
      "Pacho",
      "Paime",
      "Pandi",
      "Paratebueno",
      "Pasca",
      "Puerto Salgar",
      "Pulí",
      "Quebradanegra",
      "Quetame",
      "Quipile",
      "Apulo",
      "Ricaurte",
      "San Bernardo",
      "San Cayetano",
      "San Francisco",
      "Sesquilé",
      "Sibaté",
      "Silvania",
      "Simijaca",
      "Soacha",
      "Subachoque",
      "Suesca",
      "Supatá",
      "Susa",
      "Sutatausa",
      "Tabio",
      "Tausa",
      "Tena",
      "Tenjo",
      "Tibacuy",
      "Tibirita",
      "Tocaima",
      "Tocancipá",
      "Topaipí",
      "Ubalá",
      "Ubaque",
      "Une",
      "Útica",
      "Vianí",
      "Villagómez",
      "Villapinzón",
      "Villeta",
      "Viotá",
      "Zipacón",
      "San Juan de Río Seco",
      "Villa de San Diego de Ubate",
      "Guayabal de Síquima",
      "San Antonio del Tequendama",
      "Agua de Dios",
      "Carmen de Carupa",
      "Vergara",
      "Albán",
      "Anolaima",
      "Chía",
      "El Peñón",
      "Sopó",
      "Gama",
      "Sasaima",
      "Yacopí",
      "Fusagasugá",
      "Zipaquirá",
      "Facatativá"
    ]
  },
  {
    departamento: "Guainía",
    ciudades: [
      "Inírida",
      "Barranco Minas",
      "Mapiripana",
      "San Felipe",
      "Puerto Colombia",
      "La Guadalupe",
      "Cacahual",
      "Pana Pana",
      "Morichal"
    ]
  },
  {
    departamento: "Guaviare",
    ciudades: [
      "Calamar",
      "San José del Guaviare",
      "Miraflores",
      "El Retorno"
    ]
  },
  {
    departamento: "Huila",
    ciudades: [
      "Neiva",
      "Acevedo",
      "Agrado",
      "Aipe",
      "Algeciras",
      "Altamira",
      "Baraya",
      "Campoalegre",
      "Colombia",
      "Elías",
      "Garzón",
      "Gigante",
      "Guadalupe",
      "Hobo",
      "Iquira",
      "Isnos",
      "La Argentina",
      "La Plata",
      "Nátaga",
      "Oporapa",
      "Paicol",
      "Palermo",
      "Palestina",
      "Pital",
      "Pitalito",
      "Rivera",
      "Saladoblanco",
      "Santa María",
      "Suaza",
      "Tarqui",
      "Tesalia",
      "Tello",
      "Teruel",
      "Timaná",
      "Villavieja",
      "Yaguará",
      "San Agustín"
    ]
  },
  {
    departamento: "La Guajira",
    ciudades: [
      "Riohacha",
      "Albania",
      "Barrancas",
      "Dibula",
      "Distracción",
      "El Molino",
      "Fonseca",
      "Hatonuevo",
      "Maicao",
      "Manaure",
      "Uribia",
      "Urumita",
      "Villanueva",
      "La Jagua del Pilar",
      "San Juan del Cesar"
    ]
  },
  {
    departamento: "Magdalena",
    ciudades: [
      "Santa Marta",
      "Algarrobo",
      "Aracataca",
      "Ariguaní",
      "Cerro San Antonio",
      "Chivolo",
      "Concordia",
      "El Banco",
      "El Piñón",
      "El Retén",
      "Fundación",
      "Guamal",
      "Nueva Granada",
      "Pedraza",
      "Pivijay",
      "Plato",
      "Remolino",
      "Salamina",
      "San Zenón",
      "Santa Ana",
      "Sitionuevo",
      "Tenerife",
      "Zapayán",
      "Zona Bananera",
      "San Sebastián de Buenavista",
      "Sabanas de San Ángel",
      "Pijiño del Carmen",
      "Santa Bárbara de Pinto",
      "Pueblo Viejo",
      "Ciénaga"
    ]
  },
  {
    departamento: "Meta",
    ciudades: [
      "Uribe",
      "Villavicencio",
      "Acacías",
      "Cabuyaro",
      "Cubarral",
      "Cumaral",
      "El Calvario",
      "El Castillo",
      "El Dorado",
      "Granada",
      "Guamal",
      "Mapiripán",
      "Mesetas",
      "La Macarena",
      "Lejanías",
      "Puerto Concordia",
      "Puerto Gaitán",
      "Puerto López",
      "Puerto Lleras",
      "Puerto Rico",
      "Restrepo",
      "San Juanito",
      "San Martín",
      "Vista Hermosa",
      "Barranca de Upía",
      "Fuente de Oro",
      "San Carlos de Guaroa",
      "San Juan de Arama",
      "Castilla la Nueva"
    ]
  },
  {
    departamento: "Nariño",
    ciudades: [
      "Santacruz",
      "Pasto",
      "Albán",
      "Aldana",
      "Ancuya",
      "Barbacoas",
      "Colón",
      "Consacá",
      "Contadero",
      "Córdoba",
      "Cuaspud",
      "Cumbal",
      "Cumbitara",
      "El Charco",
      "El Peñol",
      "El Rosario",
      "El Tambo",
      "Funes",
      "Guachucal",
      "Guaitarilla",
      "Gualmatán",
      "Iles",
      "Imués",
      "Ipiales",
      "La Cruz",
      "La Florida",
      "La Llanada",
      "La Tola",
      "La Unión",
      "Leiva",
      "Linares",
      "Los Andes",
      "Magüí Payán",
      "Mallama",
      "Mosquera",
      "Nariño",
      "Olaya Herrera",
      "Ospina",
      "Francisco Pizarro",
      "Policarpa",
      "Potosí",
      "Providencia",
      "Puerres",
      "Pupiales",
      "Ricaurte",
      "Roberto Payán",
      "Samaniego",
      "Sandoná",
      "San Bernardo",
      "San Lorenzo",
      "San Pablo",
      "Santa Bárbara",
      "Sapuyes",
      "Taminango",
      "Tangua",
      "Túquerres",
      "Yacuanquer",
      "San Pedro de Cartago",
      "El Tablón de Gómez",
      "Buesaco",
      "San Andrés de Tumaco",
      "Belén",
      "Chachagüí",
      "Arboleda"
    ]
  },
  {
    departamento: "Norte de Santander",
    ciudades: [
      "Silos",
      "Cáota",
      "Toledo",
      "Mutiscua",
      "El Zulia",
      "Salazar",
      "Cucutilla",
      "Puerto Santander",
      "Gramalote",
      "El Tarra",
      "Teorama",
      "Arboledas",
      "Lourdes",
      "Bochalema",
      "Convención",
      "Hacarí",
      "Herrán",
      "Tibú",
      "San Cayetano",
      "San Calixto",
      "La Playa",
      "Chinácota",
      "Ragonvalia",
      "La Esperanza",
      "Villa del Rosario",
      "Chitagá",
      "Sardinata",
      "Ábrego",
      "Los Patios",
      "Ocaña",
      "Bucarasica",
      "Santiago",
      "Labateca",
      "Cáchira",
      "Villa Caro",
      "Durania",
      "Pamplona",
      "Pamplonita",
      "Cúcuta",
      "El Carmen"
    ]
  },
  {
    departamento: "Putumayo",
    ciudades: [
      "Mocoa",
      "Colón",
      "Orito",
      "Puerto Caicedo",
      "Puerto Guzmán",
      "Leguízamo",
      "Sibundoy",
      "San Francisco",
      "San Miguel",
      "Santiago",
      "Valle de Guamez",
      "Puerto Asís",
      "Villagarzón"
    ]
  },
  {
    departamento: "Quindío",
    ciudades: [
      "Armenia",
      "Buenavista",
      "Circasia",
      "Córdoba",
      "Filandia",
      "La Tebaida",
      "Montenegro",
      "Pijao",
      "Quimbaya",
      "Salento",
      "Calarcá",
      "Génova"
    ]
  },
  {
    departamento: "Risaralda",
    ciudades: [
      "Pereira",
      "Apía",
      "Balboa",
      "Dosquebradas",
      "Guática",
      "La Celia",
      "La Virginia",
      "Marsella",
      "Mistrató",
      "Pueblo Rico",
      "Quinchía",
      "Santuario",
      "Santa Rosa de Cabal",
      "Belén de Umbría"
    ]
  },
  {
    departamento: "Santander",
    ciudades: [
      "Puerto Wilches",
      "Puerto Parra",
      "Bucaramanga",
      "Aguada",
      "Albania",
      "Aratoca",
      "Barbosa",
      "Barichara",
      "Barrancabermeja",
      "Betulia",
      "Bolívar",
      "Cabrera",
      "California",
      "Carcasí",
      "Cepitá",
      "Cerrito",
      "Charalá",
      "Charta",
      "Chipatá",
      "Cimitarra",
      "Concepción",
      "Confines",
      "Contratación",
      "Coromoro",
      "Curití",
      "El Guacamayo",
      "El Playón",
      "Encino",
      "Enciso",
      "Florián",
      "Floridablanca",
      "Galán",
      "Gambita",
      "Girón",
      "Guaca",
      "Guadalupe",
      "Guapotá",
      "Guavatá",
      "Güepsa",
      "Jesús María",
      "Jordán",
      "La Belleza",
      "Landázuri",
      "La Paz",
      "Lebríja",
      "Los Santos",
      "Macaravita",
      "Málaga",
      "Matanza",
      "Mogotes",
      "Molagavita",
      "Ocamonte",
      "Oiba",
      "Onzaga",
      "Palmar",
      "Páramo",
      "Piedecuesta",
      "Pinchote",
      "Puente Nacional",
      "Rionegro",
      "San Andrés",
      "San Gil",
      "San Joaquín",
      "San Miguel",
      "Santa Bárbara",
      "Simacota",
      "Socorro",
      "Suaita",
      "Sucre",
      "Suratá",
      "Tona",
      "Vélez",
      "Vetas",
      "Villanueva",
      "Zapatoca",
      "Palmas del Socorro",
      "San Vicente de Chucurí",
      "San José de Miranda",
      "Santa Helena del Opón",
      "Sabana de Torres",
      "El Carmen de Chucurí",
      "Valle de San José",
      "San Benito",
      "Hato",
      "Chimá",
      "Capitanejo",
      "El Peñón"
    ]
  },
  {
    departamento: "Sucre",
    ciudades: [
      "Sincelejo",
      "Buenavista",
      "Caimito",
      "Coloso",
      "Coveñas",
      "Chalán",
      "El Roble",
      "Galeras",
      "Guaranda",
      "La Unión",
      "Los Palmitos",
      "Majagual",
      "Morroa",
      "Ovejas",
      "Palmito",
      "San Benito Abad",
      "San Marcos",
      "San Onofre",
      "San Pedro",
      "Sucre",
      "Tolú Viejo",
      "San Luis de Sincé",
      "San Juan de Betulia",
      "Santiago de Tolú",
      "Sampués",
      "Corozal"
    ]
  },
  {
    departamento: "Tolima",
    ciudades: [
      "Alpujarra",
      "Alvarado",
      "Ambalema",
      "Armero",
      "Ataco",
      "Cajamarca",
      "Chaparral",
      "Coello",
      "Coyaima",
      "Cunday",
      "Dolores",
      "Espinal",
      "Falan",
      "Flandes",
      "Fresno",
      "Guamo",
      "Herveo",
      "Honda",
      "Icononzo",
      "Mariquita",
      "Melgar",
      "Murillo",
      "Natagaima",
      "Ortega",
      "Palocabildo",
      "Piedras",
      "Planadas",
      "Prado",
      "Purificación",
      "Rio Blanco",
      "Roncesvalles",
      "Rovira",
      "Saldaña",
      "Santa Isabel",
      "Venadillo",
      "Villahermosa",
      "Villarrica",
      "Valle de San Juan",
      "Carmen de Apicalá",
      "San Luis",
      "San Antonio",
      "Casabianca",
      "Anzoátegui",
      "Ibagué",
      "Líbano",
      "Lérida",
      "Suárez"
    ]
  },
  {
    departamento: "Valle del Cauca",
    ciudades: [
      "El Dovio",
      "Roldanillo",
      "Argelia",
      "Sevilla",
      "Zarzal",
      "El Cerrito",
      "Cartago",
      "Caicedonia",
      "El Cairo",
      "La Unión",
      "Restrepo",
      "Dagua",
      "Guacarí",
      "Ansermanuevo",
      "Bugalagrande",
      "La Victoria",
      "Ginebra",
      "Yumbo",
      "Obando",
      "Bolívar",
      "Cali",
      "San Pedro",
      "Guadalajara de Buga",
      "Calima",
      "Andalucía",
      "Pradera",
      "Yotoco",
      "Palmira",
      "Riofrío",
      "Alcalá",
      "Versalles",
      "El Águila",
      "Toro",
      "Candelaria",
      "La Cumbre",
      "Ulloa",
      "Trujillo",
      "Vijes",
      "Tuluá",
      "Florida",
      "Jamundí",
      "Buenaventura"
    ]
  },
  {
    departamento: "Vaupés",
    ciudades: [
      "Mitú",
      "Carurú",
      "Taraira",
      "Papunahua",
      "Yavaraté",
      "Pacoa"
    ]
  },
  {
    departamento: "Vichada",
    ciudades: [
      "Puerto Carreño",
      "La Primavera",
      "Santa Rosalía",
      "Cumaribo"
    ]
  }
];
